DEBUGFLAGS := -DDEBUG -Og -ggdb
RELEASEFLAGS := -O2
ARM-ARCHFLAGS :=-mcpu=cortex-a72 -mfloat-abi=hard -mfpu=neon-fp-armv8
CXXLANGFLAGS := -std=gnu++20
WARNINGFLAGS := -Wall -Wshadow=local -Werror -Wno-error=unused-variable -Wno-error=unused-but-set-variable
MAKESUPPORTFLAGS := -MMD -MP
X86-TEST-CXXFLAGS := $(CXXLANGFLAGS) $(DEBUGFLAGS) $(WARNINGFLAGS) $(MAKESUPPORTFLAGS)
ARM-DEBUG-CXXFLAGS := $(CXXLANGFLAGS) $(DEBUGFLAGS) $(WARNINGFLAGS) $(MAKESUPPORTFLAGS)
ARM-RELEASE-CXXFLAGS := $(CXXLANGFLAGS) $(RELEASEFLAGS) $(WARNINGFLAGS) $(ARM-ARCHFLAGS) $(MAKESUPPORTFLAGS)
X86-TEST-LDFLAGS :=
ARM-DEBUG-LDFLAGS := -pthread
ARM-RELEASE-LDFLAGS := -s -pthread
