DEBUGFLAGS := -DDEBUG -Og -ggdb
RELEASEFLAGS := -O2
RPI4-ARCHFLAGS :=-mcpu=cortex-a72 -mfloat-abi=hard -mfpu=neon-fp-armv8
CXXLANGFLAGS := -std=gnu++20
WARNINGFLAGS := -Wall -Wshadow=local -Werror -Wno-error=unused-variable -Wno-error=unused-but-set-variable
MAKESUPPORTFLAGS := -MMD -MP
HOST-TEST-CXXFLAGS := $(CXXLANGFLAGS) $(DEBUGFLAGS) $(WARNINGFLAGS) $(MAKESUPPORTFLAGS)
RPI4-DEBUG-CXXFLAGS := $(CXXLANGFLAGS) $(DEBUGFLAGS) $(WARNINGFLAGS) $(MAKESUPPORTFLAGS)
RPI4-RELEASE-CXXFLAGS := $(CXXLANGFLAGS) $(RELEASEFLAGS) $(WARNINGFLAGS) $(RPI4-ARCHFLAGS) $(MAKESUPPORTFLAGS)
HOST-TEST-LDFLAGS :=
RPI4-DEBUG-LDFLAGS := -pthread
RPI4-RELEASE-LDFLAGS := -s -pthread
