SRCDIR := src/
INCDIR := inc/
TESTDIR := test/
OBJ_DIR := obj/
TEST_DIR := $(OBJ_DIR)host_test
DEBUG_DIR := $(OBJ_DIR)host_debug
RELEASE_DIR := $(OBJ_DIR)host_release
DEBUG-LIBS := -lncurses -lgpiod
RELEASE-LIBS := -lncurses -lgpiod
TEST-LIBS :=-lgtest -lgtest_main -lgmock -lncurses -lgpiod
