X86-TEST-BUILDRECEIPE = $(X86-CXX) $(INC) $(X86-TEST-CXXFLAGS) -c $< -o $@
ARM-RELEASE-BUILDRECEIPE = $(ARM-CXX) $(INC) $(ARM-RELEASE-CXXFLAGS) -c $< -o $@
ARM-DEBUG-BUILDRECEIPE = $(ARM-CXX) $(INC) $(ARM-DEBUG-CXXFLAGS) -c $< -o $@

X86-TEST-LINKRECEIPE = $(X86-CXX) $(X86-TEST-LDFLAGS) -o $@ $^ $(X86-TEST-LIBS)
ARM-DEBUG-LINKRECEIPE = $(ARM-CXX) $(ARM-DEBUG-LDFLAGS) -o $@ $^ $(ARM-DEBUG-LIBS)
ARM-RELEASE-LINKRECEIPE = $(ARM-CXX) $(ARM-RELEASE-LDFLAGS) -o $@ $^ $(ARM-RELEASE-LIBS)

MKDIR-RECEIPE = mkdir -p $@
