HOST-TEST-BUILDRECEIPE = $(HOST-CXX) $(INC) $(HOST-TEST-CXXFLAGS) -c $< -o $@
ARM-RELEASE-BUILDRECEIPE = $(ARM-LINUX-GNUEABIHF-CXX) $(INC) $(ARM-RELEASE-CXXFLAGS) -c $< -o $@
ARM-DEBUG-BUILDRECEIPE = $(ARM-LINUX-GNUEABIHF-CXX) $(INC) $(ARM-DEBUG-CXXFLAGS) -c $< -o $@

HOST-TEST-LINKRECEIPE = $(HOST-CXX) $(HOST-TEST-LDFLAGS) -o $@ $^ $(HOST-TEST-LIBS)
ARM-DEBUG-LINKRECEIPE = $(ARM-LINUX-GNUEABIHF-CXX) $(ARM-DEBUG-LDFLAGS) -o $@ $^ $(ARM-DEBUG-LIBS)
ARM-RELEASE-LINKRECEIPE = $(ARM-LINUX-GNUEABIHF-CXX) $(ARM-RELEASE-LDFLAGS) -o $@ $^ $(ARM-RELEASE-LIBS)

MKDIR-RECEIPE = mkdir -p $@
