HOST-TEST-BUILDRECEIPE = $(HOST-CXX) $(INC) $(HOST-TEST-CXXFLAGS) -c $< -o $@
HOST-DEBUG-BUILDRECEIPE = $(HOST-CXX) $(INC) $(HOST-DEBUG-CXXFLAGS) -c $< -o $@
HOST-RELEASE-BUILDRECEIPE = $(HOST-CXX) $(INC) $(HOST-RELEASE-CXXFLAGS) -c $< -o $@
RPI4-RELEASE-BUILDRECEIPE = $(ARM-LINUX-GNUEABIHF-CXX) $(INC) $(RPI4-RELEASE-CXXFLAGS) -c $< -o $@
RPI4-PROFILE-BUILDRECEIPE = $(ARM-LINUX-GNUEABIHF-CXX) $(INC) $(RPI4-PROFILE-CXXFLAGS) -c $< -o $@
RPI4-DEBUG-BUILDRECEIPE = $(ARM-LINUX-GNUEABIHF-CXX) $(INC) $(RPI4-DEBUG-CXXFLAGS) -c $< -o $@

HOST-TEST-LINKRECEIPE = $(HOST-CXX) $(HOST-TEST-LDFLAGS) -o $@ $^ $(HOST-TEST-LIBS)
HOST-DEBUG-LINKRECEIPE = $(HOST-CXX) $(HOST-DEBUG-LDFLAGS) -o $@ $^ $(HOST-DEBUG-LIBS)
HOST-RELEASE-LINKRECEIPE = $(HOST-CXX) $(HOST-RELEASE-LDFLAGS) -o $@ $^ $(HOST-RELEASE-LIBS)
RPI4-DEBUG-LINKRECEIPE = $(ARM-LINUX-GNUEABIHF-CXX) $(RPI4-DEBUG-LDFLAGS) -o $@ $^ $(RPI4-DEBUG-LIBS)
RPI4-RELEASE-LINKRECEIPE = $(ARM-LINUX-GNUEABIHF-CXX) $(RPI4-RELEASE-LDFLAGS) -o $@ $^ $(RPI4-RELEASE-LIBS)
RPI4-PROFILE-LINKRECEIPE = $(ARM-LINUX-GNUEABIHF-CXX) $(RPI4-PROFILE-LDFLAGS) -o $@ $^ $(RPI4-PROFILE-LIBS)

MKDIR-RECEIPE = mkdir -p $@
