ROOTDIR := $(TOP)

INCDIRS += $(ROOTDIR)$(INCDIR)
ROOTSRC := $(ROOTDIR)$(SRCDIR)
ROOTTEST := $(ROOTDIR)$(TESTDIR)

ROOTTESTODIR := $(TESTOBJ_DIR)/$(ROOTDIR)
ROOTTESTDBGODIR := $(TESTDBGOBJ_DIR)/$(ROOTDIR)
ROOTDEBUGODIR := $(DEBUGOBJ_DIR)/$(ROOTDIR)
ROOTRELEASEODIR := $(RELEASEOBJ_DIR)/$(ROOTDIR)
ODIRS += $(ROOTTESTODIR) $(ROOTDEBUGODIR) $(ROOTRELEASEODIR) $(ROOTTESTDBGODIR)

ROOTCXXFILES := $(wildcard $(ROOTSRC)*.cpp)
ROOTTESTCXXFILES := $(wildcard $(ROOTTEST)*.cpp)
ROOTDEBUG_OFILES := $(patsubst $(ROOTSRC)%,$(ROOTDEBUGODIR)%,$(patsubst %.cpp,%.cpp.o,$(ROOTCXXFILES)))
ROOTRELEASE_OFILES := $(patsubst $(ROOTSRC)%,$(ROOTRELEASEODIR)%,$(patsubst %.cpp,%.cpp.o,$(ROOTCXXFILES)))
ROOTTESTDBG_OFILES := $(patsubst $(ROOTSRC)%,$(ROOTTESTDBGODIR)%,$(patsubst %.cpp,%.cpp.o,$(ROOTCXXFILES)))

ROOTTESTDBG_OFILES := $(filter-out $(ROOTTESTDBGODIR)main.cpp.o, $(ROOTTESTDBG_OFILES))

ROOTTEST_OFILES := $(patsubst $(ROOTTEST)%,$(ROOTTESTODIR)%,$(patsubst %.cpp,%.cpp.o,$(ROOTTESTCXXFILES)))
RELEASE_OFILES += $(ROOTRELEASE_OFILES)
DEBUG_OFILES += $(ROOTDEBUG_OFILES)
TEST_OFILES += $(ROOTTEST_OFILES) $(ROOTTESTDBG_OFILES)
ALLOFILES += $(ROOTDEBUG_OFILES) $(ROOTRELEASE_OFILES) $(ROOTTEST_OFILES) $(ROOTTESTDBG_OFILES)

$(ROOTDEBUGODIR)%.cpp.o: $(ROOTSRC)%.cpp | $(ROOTDEBUGODIR)
	$(RPI4-DEBUG-BUILDRECEIPE)

$(ROOTRELEASEODIR)%.cpp.o: $(ROOTSRC)%.cpp | $(ROOTRELEASEODIR)
	$(RPI4-RELEASE-BUILDRECEIPE)

$(ROOTTESTDBGODIR)%.cpp.o: $(ROOTSRC)%.cpp | $(ROOTTESTDBGODIR)
	$(HOST-TEST-BUILDRECEIPE)

$(ROOTTESTODIR)%.cpp.o: $(ROOTTEST)%.cpp | $(ROOTTESTODIR)
	$(HOST-TEST-BUILDRECEIPE)
