ROOTDIR := $(TOP)

INCDIRS += $(ROOTDIR)$(INCDIR)
ROOTSRC := $(ROOTDIR)$(SRCDIR)
ROOTTEST := $(ROOTDIR)$(TESTDIR)

ROOTTESTODIR := $(TESTOBJ_DIR)/$(ROOTDIR)
ROOTDEBUGODIR := $(DEBUGOBJ_DIR)/$(ROOTDIR)
ROOTRELEASEODIR := $(RELEASEOBJ_DIR)/$(ROOTDIR)
ODIRS += $(ROOTTESTODIR) $(ROOTDEBUGODIR) $(ROOTRELEASEODIR)

ROOTCXXFILES := $(wildcard $(ROOTSRC)*.cpp)
ROOTTESTCXXFILES := $(wildcard $(ROOTTEST)*.cpp)
ROOTDEBUG_OFILES := $(patsubst $(ROOTSRC)%,$(ROOTDEBUGODIR)%,$(patsubst %.cpp,%.cpp.o,$(ROOTCXXFILES)))
ROOTRELEASE_OFILES := $(patsubst $(ROOTSRC)%,$(ROOTRELEASEODIR)%,$(patsubst %.cpp,%.cpp.o,$(ROOTCXXFILES)))
ROOTTEST_OFILES := $(patsubst $(ROOTSRC)%,$(ROOTTESTODIR)%,$(patsubst %.cpp,%.cpp.o,$(ROOTCXXFILES)))
ROOTTEST_OFILES += $(patsubst $(ROOTSRC)%,$(ROOTTESTODIR)%,$(patsubst %.cpp,%.cpp.o,$(ROOTTESTCXXFILES)))
RELEASE_OFILES += $(ROOTRELEASE_OFILES)
DEBUG_OFILES += $(ROOTDEBUG_OFILES)
TEST_OFILES += $(ROOTTEST_OFILES)
ALLOFILES += $(ROOTDEBUG_OFILES) $(ROOTRELEASE_OFILES) $(ROOTTEST_OFILES)

$(ROOTDEBUGODIR)%.cpp.o: $(ROOTSRC)%.cpp | $(ROOTDEBUGODIR)
	$(ARM-DEBUG-BUILDRECEIPE)

$(ROOTRELEASEODIR)%.cpp.o: $(ROOTSRC)%.cpp | $(ROOTRELEASEODIR)
	$(ARM-RELEASE-BUILDRECEIPE)

$(ROOTTESTODIR)%.cpp.o: $(ROOTSRC)%.cpp | $(ROOTTESTODIR)
	$(HOST-TEST-BUILDRECEIPE)

$(ROOTTESTODIR)%.cpp.o: $(ROOTTEST)%.cpp | $(ROOTTESTODIR)
	$(HOST-TEST-BUILDRECEIPE)
