DIR := $(TOP)

INCDIRS += $(DIR)$(INCDIR)
SRC := $(DIR)$(SRCDIR)
TEST := $(DIR)$(TESTDIR)

HOSTTESTODIR := $(HOST_TEST_DIR)/$(DIR)
HOSTDEBUGODIR := $(HOST_DEBUG_DIR)/$(DIR)
HOSTRELEASEODIR := $(HOST_RELEASE_DIR)/$(DIR)
RPI4DEBUGODIR := $(RPI4_DEBUG_DIR)/$(DIR)
RPI4RELEASEODIR := $(RPI4_RELEASE_DIR)/$(DIR)
RPI4PROFILEODIR := $(RPI4_PROFILE_DIR)/$(DIR)

ODIRS += $(HOSTTESTODIR) $(HOSTDEBUGODIR) $(HOSTRELEASEODIR) $(RPI4DEBUGODIR) $(RPI4RELEASEODIR) $(RPI4PROFILEODIR)

CXXFILES := $(wildcard $(SRC)*.cpp)
TESTCXXFILES := $(wildcard $(TEST)*.cpp)

RPI4DEBUG_OFILES := $(patsubst $(SRC)%,$(RPI4DEBUGODIR)%,$(patsubst %.cpp,%.cpp.o,$(CXXFILES)))
RPI4RELEASE_OFILES := $(patsubst $(SRC)%,$(RPI4RELEASEODIR)%,$(patsubst %.cpp,%.cpp.o,$(CXXFILES)))
RPI4PROFILE_OFILES := $(patsubst $(SRC)%,$(RPI4PROFILEODIR)%,$(patsubst %.cpp,%.cpp.o,$(CXXFILES)))
HOSTDEBUG_OFILES := $(patsubst $(SRC)%,$(HOSTDEBUGODIR)%,$(patsubst %.cpp,%.cpp.o,$(CXXFILES)))
HOSTRELEASE_OFILES := $(patsubst $(SRC)%,$(HOSTRELEASEODIR)%,$(patsubst %.cpp,%.cpp.o,$(CXXFILES)))
HOSTTEST_OFILES := $(patsubst $(TEST)%,$(HOSTTESTODIR)%,$(patsubst %.cpp,%.cpp.o,$(TESTCXXFILES)))
RPI4_RELEASE_OFILES += $(RPI4RELEASE_OFILES)
RPI4_PROFILE_OFILES += $(RPI4PROFILE_OFILES)
RPI4_DEBUG_OFILES += $(RPI4DEBUG_OFILES)
HOST_DEBUG_OFILES += $(HOSTDEBUG_OFILES)
HOST_RELEASE_OFILES += $(HOSTRELEASE_OFILES)
HOST_TEST_OFILES += $(HOSTTEST_OFILES) $(HOSTDEBUG_OFILES)
HOST_TEST_OFILES := $(filter-out $(HOSTDEBUGODIR)main.cpp.o, $(HOST_TEST_OFILES))
ALLOFILES += $(RPI4_RELEASE_OFILES) $(RPI4_DEBUG_OFILES) $(RPI4_PROFILE_OFILES) $(HOST_TEST_OFILES) $(HOST_DEBUG_OFILES) $(HOST_RELEASE_OFILES)

$(RPI4DEBUGODIR)%.cpp.o: $(SRC)%.cpp | $(RPI4DEBUGODIR)
	$(RPI4-DEBUG-BUILDRECEIPE)

$(RPI4RELEASEODIR)%.cpp.o: $(SRC)%.cpp | $(RPI4RELEASEODIR)
	$(RPI4-RELEASE-BUILDRECEIPE)

$(RPI4PROFILEODIR)%.cpp.o: $(SRC)%.cpp | $(RPI4PROFILEODIR)
	$(RPI4-PROFILE-BUILDRECEIPE)

$(HOSTDEBUGODIR)%.cpp.o: $(SRC)%.cpp | $(HOSTDEBUGODIR)
	$(HOST-DEBUG-BUILDRECEIPE)

$(HOSTRELEASEODIR)%.cpp.o: $(SRC)%.cpp | $(HOSTRELEASEODIR)
	$(HOST-RELEASE-BUILDRECEIPE)

$(HOSTTESTODIR)%.cpp.o: $(TEST)%.cpp | $(HOSTTESTODIR)
	$(HOST-TEST-BUILDRECEIPE)
