2DGLXDIR := $(TOP)$(notdir $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST)))))/

INCDIRS += $(2DGLXDIR)$(INCDIR)
2DGLXSRC := $(2DGLXDIR)$(SRCDIR)
2DGLXTEST := $(2DGLXDIR)$(TESTDIR)

2DGLXTESTODIR := $(TESTOBJ_DIR)/$(2DGLXDIR)
2DGLXTESTDBGODIR := $(TESTDBGOBJ_DIR)/$(2DGLXDIR)
2DGLXDEBUGODIR := $(DEBUGOBJ_DIR)/$(2DGLXDIR)
2DGLXRELEASEODIR := $(RELEASEOBJ_DIR)/$(2DGLXDIR)
ODIRS += $(2DGLXTESTODIR) $(2DGLXDEBUGODIR) $(2DGLXRELEASEODIR) $(2DGLXTESTDBGODIR)

2DGLXCXXFILES := $(wildcard $(2DGLXSRC)*.cpp)
2DGLXTESTCXXFILES := $(wildcard $(2DGLXTEST)*.cpp)
2DGLXDEBUG_OFILES := $(patsubst $(2DGLXSRC)%,$(2DGLXDEBUGODIR)%,$(patsubst %.cpp,%.cpp.o,$(2DGLXCXXFILES)))
2DGLXRELEASE_OFILES := $(patsubst $(2DGLXSRC)%,$(2DGLXRELEASEODIR)%,$(patsubst %.cpp,%.cpp.o,$(2DGLXCXXFILES)))
2DGLXTESTDBG_OFILES := $(patsubst $(2DGLXSRC)%,$(2DGLXTESTDBGODIR)%,$(patsubst %.cpp,%.cpp.o,$(2DGLXCXXFILES)))
2DGLXTEST_OFILES := $(patsubst $(2DGLXTEST)%,$(2DGLXTESTODIR)%,$(patsubst %.cpp,%.cpp.o,$(2DGLXTESTCXXFILES)))
RELEASE_OFILES += $(2DGLXRELEASE_OFILES)
DEBUG_OFILES += $(2DGLXDEBUG_OFILES)
TEST_OFILES += $(2DGLXTEST_OFILES) $(2DGLXTESTDBG_OFILES)
ALLOFILES += $(2DGLXDEBUG_OFILES) $(2DGLXRELEASE_OFILES) $(2DGLXTEST_OFILES) $(2DGLXTESTDBG_OFILES)

$(2DGLXDEBUGODIR)%.cpp.o: $(2DGLXSRC)%.cpp | $(2DGLXDEBUGODIR)
	$(RPI4-DEBUG-BUILDRECEIPE)

$(2DGLXRELEASEODIR)%.cpp.o: $(2DGLXSRC)%.cpp | $(2DGLXRELEASEODIR)
	$(RPI4-RELEASE-BUILDRECEIPE)

$(2DGLXTESTDBGODIR)%.cpp.o: $(2DGLXSRC)%.cpp | $(2DGLXTESTDBGODIR)
	$(HOST-TEST-BUILDRECEIPE)

$(2DGLXTESTODIR)%.cpp.o: $(2DGLXTEST)%.cpp | $(2DGLXTESTODIR)
	$(HOST-TEST-BUILDRECEIPE)
