MATRIXDIR := $(TOP)$(notdir $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST)))))/

INCDIRS += $(MATRIXDIR)$(INCDIR)
MATRIXSRC := $(MATRIXDIR)$(SRCDIR)
MATRIXTEST := $(MATRIXDIR)$(TESTDIR)

MATRIXTESTODIR := $(TESTOBJ_DIR)/$(MATRIXDIR)
MATRIXTESTDBGODIR := $(TESTDBGOBJ_DIR)/$(MATRIXDIR)
MATRIXDEBUGODIR := $(DEBUGOBJ_DIR)/$(MATRIXDIR)
MATRIXRELEASEODIR := $(RELEASEOBJ_DIR)/$(MATRIXDIR)
ODIRS += $(MATRIXTESTODIR) $(MATRIXDEBUGODIR) $(MATRIXRELEASEODIR) $(MATRIXTESTDBGODIR)

MATRIXCXXFILES := $(wildcard $(MATRIXSRC)*.cpp)
MATRIXTESTCXXFILES := $(wildcard $(MATRIXTEST)*.cpp)
MATRIXDEBUG_OFILES := $(patsubst $(MATRIXSRC)%,$(MATRIXDEBUGODIR)%,$(patsubst %.cpp,%.cpp.o,$(MATRIXCXXFILES)))
MATRIXRELEASE_OFILES := $(patsubst $(MATRIXSRC)%,$(MATRIXRELEASEODIR)%,$(patsubst %.cpp,%.cpp.o,$(MATRIXCXXFILES)))
MATRIXTESTDBG_OFILES := $(patsubst $(MATRIXSRC)%,$(MATRIXTESTDBGODIR)%,$(patsubst %.cpp,%.cpp.o,$(MATRIXCXXFILES)))
MATRIXTEST_OFILES := $(patsubst $(MATRIXTEST)%,$(MATRIXTESTODIR)%,$(patsubst %.cpp,%.cpp.o,$(MATRIXTESTCXXFILES)))
RELEASE_OFILES += $(MATRIXRELEASE_OFILES)
DEBUG_OFILES += $(MATRIXDEBUG_OFILES)
TEST_OFILES += $(MATRIXTEST_OFILES) $(MATRIXTESTDBG_OFILES)
ALLOFILES += $(MATRIXDEBUG_OFILES) $(MATRIXRELEASE_OFILES) $(MATRIXTEST_OFILES) $(MATRIXTESTDBG_OFILES)

$(MATRIXDEBUGODIR)%.cpp.o: $(MATRIXSRC)%.cpp | $(MATRIXDEBUGODIR)
	$(RPI4-DEBUG-BUILDRECEIPE)

$(MATRIXRELEASEODIR)%.cpp.o: $(MATRIXSRC)%.cpp | $(MATRIXRELEASEODIR)
	$(RPI4-RELEASE-BUILDRECEIPE)

$(MATRIXTESTDBGODIR)%.cpp.o: $(MATRIXSRC)%.cpp | $(MATRIXTESTDBGODIR)
	$(HOST-TEST-BUILDRECEIPE)

$(MATRIXTESTODIR)%.cpp.o: $(MATRIXTEST)%.cpp | $(MATRIXTESTODIR)
	$(HOST-TEST-BUILDRECEIPE)
